export const handleError = (error) => {
  console.error(`Failure when doing: ${error.name} ${error}`);
};
